version: '3'
services:
  wordpress:
    image: visiblevc/wordpress:0.16.0-php7.1
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./src:/app/wp-content/plugins/wordpress-version-control
    environment:
      DB_NAME: wordpress
      DB_PASS: root
  db:
    image: mariadb:10
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80
volumes:
  data:
